# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://novalegra.github.io
title: Anna Quinlan
email: annaquinlancollege@gmail.com
author: Anna Quinlan
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2018 Anna Quinlan. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/novalegra
  - title: resume
    url: https://docs.google.com/document/d/1TVMioGF8rQeawKsibDF4kSYug8OcCr58mLh55V-krHQ/edit?usp=sharing

#  - title: linkedin
#    url: www.linkedin.com/in/anna-quinlan
