# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://novalegra.github.io
title: Anna Quinlan
email: aquinlan@stanford.edu
author: Anna Quinlan
description: >
  I'm fascinated by novel uses of technology and big data to solve problems in healthcare and research, and
  am passionate about improving indigenous representation in STEM fields. I ultimately
  hope to create tools to improve diabetes care in underserved communities. My other interests
  include hiking, long-distance running, and photography. 
copyright: 'Copyright &copy; 2019 Anna Quinlan. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/novalegra
  - title: resume
    url: https://docs.google.com/document/d/1TVMioGF8rQeawKsibDF4kSYug8OcCr58mLh55V-krHQ/edit?usp=sharing

  - title: linkedin
    url: https://linkedin.com/in/anna-quinlan
